import 'package:flutter/material.dart';

final List<Map<String, dynamic>> listOfWatches = [
  {
    'name': 'Apple Watch',
    'year': '2020',
    'image': 'assets/images/apple_watch.png',
    'price': '\$199.00',
    'oldPrice': '\$299.00',
    'isFavorite': true,
    'material': 'brown leather case',
    'color': Colors.black,
  },
  {
    'name': 'Dan Henry',
    'year': '2019',
    'image': 'assets/images/dan_henry.png',
    'price': '\$159.00',
    'oldPrice': '\$200.00',
    'isFavorite': false,
    'material': 'Leather fashion',
    'color': Colors.red,
  },
  {
    'name': 'Casima',
    'year': '2015',
    'image': 'assets/images/casimas.png',
    'price': '\$299.00',
    'oldPrice': '\$355.00',
    'isFavorite': true,
    'material': 'brown leather case',
    'color': Colors.orange,
  },
  {
    'name': 'Laurent Ferrier',
    'year': '2013',
    'image': 'assets/images/laurent_ferrier.png',
    'price': '\$555.00',
    'oldPrice': '\$699.00',
    'isFavorite': false,
    'material': 'brown leather case',
    'color': Colors.blue,
  },
  {
    'name': 'Ferrier Classic',
    'year': '2012',
    'image': 'assets/images/laurent-ferrier-classic-micro-rotor-white-gold-ice-blue.png',
    'price': '\$299.00',
    'oldPrice': '\$399.00',
    'isFavorite': true,
    'material': 'brown leather case',
    'color': Colors.brown,
  },
  {
    'name': 'Hamilton',
    'year': '2020',
    'image': 'assets/images/hamilton.png',
    'price': '\$159.00',
    'oldPrice': '\$299.00',
    'isFavorite': false,
    'material': 'brown leather case',
    'color': Colors.purpleAccent,
  },
];
